CREATE DATABASE IF NOT EXISTS tourwithRK;
USE tourwithRK;

CREATE TABLE IF NOT EXISTS feedback (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    feedback TEXT NOT NULL,
    image_path VARCHAR(255)
);
ALTER TABLE feedback
ADD CONSTRAINT unique_email UNIQUE (email);

CREATE TABLE IF NOT EXISTS bookings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    number_of_guests INT NOT NULL,
    date_of_arrival DATE NOT NULL,
    vehicle VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);